# Generated by Django 3.2.1 on 2021-06-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_id', models.IntegerField(blank=True, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pi Camera',
                'verbose_name_plural': 'Pi Cameras',
            },
        ),
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Accesso', 'verbose_name_plural': 'Accessi'},
        ),
    ]
