# Generated by Django 3.2.1 on 2021-06-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210626_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='TImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('face_num', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tcamera')),
            ],
            options={
                'verbose_name': 'TImage',
                'verbose_name_plural': 'TImages',
            },
        ),
    ]
