# Generated by Django 3.2.1 on 2021-06-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRecognized',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='media/recognized')),
            ],
            options={
                'verbose_name': 'TRecognized',
                'verbose_name_plural': 'TRecognized',
            },
        ),
        migrations.AddField(
            model_name='access',
            name='recognized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trecognized'),
        ),
    ]
